// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnnphgtzdqgzrdwvyltq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRubnBoZ3R6ZHFnenJkd3Z5bHRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDQ5ODMsImV4cCI6MjA2OTcyMDk4M30.vdhKnzPy2QG1wLBCDDuMyxLr_e5VJ5TxdZ8ekViKC6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});